project:
  type: website
  output-dir: docs

website:
  title: "Drip Knowledge Center"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: Getting Started
        href: site/getting-started/index.qmd
      - text: Strategy
        href: site/strategy/index.qmd
      - text: Tokenomics
        href: site/tokenomics/index.qmd
      - text: Tools & Resources
        href: site/tools-resources/index.qmd
  
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: index.qmd
  #     - section: site/getting-started/index.qmd
  #     - section: site/strategy/index.qmd
  #     - section: site/tokenomics/index.qmd
  #     - section: site/tools-resources/index.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



