---
title: "Getting Started"
---

Getting Started with DRIP
THE OFFICIAL TOKEN OF THE DRIP NETWORK IS DRIP (BEP-20) ON THE BINANCE SMART BLOCKCHAIN (BSC) THAT CAPTURES VALUE BY BEING SCARCE, DEFLATIONARY, CENSORSHIP RESISTANT, AND BY BEING BUILT ON A ROBUST, TRULY DECENTRALIZED BLOCKCHAIN.

Setup
Download the following apps
1.	Crypto.com 
 

2.	MetaMask
 

3.	DUO
 

Create a Crypto.com Account
1.	Go through the steps as seen on the on the screen
a.	You’ll need your photo ID at some point
b.	Here’s a video to help
i.	Another helpful link giving a full overview of the app
c.	It may take a bit to validate your account, could be 5 min or over 1 day in some cases
d.	Go to Settings and Enable Face ID/Touch ID

2.	Setup 2-Factor Authentication
a.	Go to Settings in the top left of the crypto.com app
b.	2-Factor Authentication
c.	Enable 2FA
d.	Copy code 
e.	Open DUO
i.	Click on Add + to add an account
ii.	Scroll down to “Add other account”
iii.	Paste your code
f.	Go back to crypto.com app and click Proceed to Verify
g.	This ^ will generate a new 6-digit passcode in the DUO app
h.	Switch to DUO, and copy the 6-digit passcode
i.	Switch back to crypto.com, paste it, and click Enable 2FA


Create a MetaMask Wallet
1.	Open MetaMask and click Get Started
2.	Click on “Create a Wallet” and on the next window click on “I agree” if you would like to help improve MetaMask or click on “No Thanks” to proceed.
3.	Create a strong password for your wallet.
4.	SUPER IMPORTANT: Securely store the seed phrase for your wallet
a.	Click on “Click here to reveal secret words” to show the seed phrase.
b.	MetaMask requires that you store your seed phrase in a safe place. It is the only way to recover your funds should your device crash or your browser reset. We recommend you write it down. The most common method is to write your 12-word phrase on a piece of paper and store it safely in a place where only you have access. Note: if you lose your seed phrase, MetaMask can’t help you recover your wallet and your funds will be lost forever.
c.	Never share your seed phrase or your private key to anyone or any site, unless you want them to have full control over your funds.
 
5.	Click Next
6.	Seed phrase confirmation
Confirm your secret backup phrase by clicking on each word in the order in which the words were presented on the previous screen. Click on “Confirm” to proceed.
 
 
You should see “Congratulations!” now.

Add Binance Smart Chain to MetaMask Wallet
1.	Open MetaMask
2.	Open the side bar menu (top left)
3.	Click Settings
4.	Click Networks
5.	Add Network and enter the info below
a.	Network Name: Smart Chain
b.	New RPC URL: https://bsc-dataseed.binance.org/
c.	ChainID: 56
d.	Symbol: BNB
e.	Block Explorer URL: https://bscscan.com

Connect Crypto.com to MetaMask!
1.	Open crypto.com
2.	Go to Track and search for “BNB” (Binance Coin) 
3.	Click Buy BNB
4.	You’ll need to Add a Credit or Debit Card
a.	Go through the steps required to do this. You may need to have your online banking app ready as it may send a small transaction to your card with a special code you need to extract from it.
5.	Enter the amount of BNB you wish to acquire
a.	For example, right now I can purchase 1.5 BNB for $566.39
6.	After buying BNB, go to Accounts (bottom menu)
7.	Click on the Crypto Wallet dropdown and select Binance Coin
8.	Click Transfer, then Withdraw
9.	Click External Wallet
10.	 Click the ‘+’ at the top right
11.	 Click Wallet Address
12.	 IMPORTANT: Switch network to BSC
13.	You’ll need to add your MetaMask Wallet address in the BNB Wallet Address section
a.	Go back to MetaMask
b.	Copy address (right above the send button)
14.	Go back to the crypto.com app and paste it in the BNB Wallet Address section
15.	 Add a wallet name
16.	 Click Continue. This could take time to add a new address.
17.	Once wallet is added, click Withdraw BNB
18.	 Enter amount of BNB to transfer to MetaMask (This is the amount you want to use to purchase DRIP). 
19.	 Click Withdraw
20.	 It’ll ask you to get the 6-digit code from your DUO app. Go to DUO and copy it. Come back to crypto.com and paste it.
21.	Done.


BUY DRIP!
1.	Open MetaMask
2.	Open the sidebar menu
3.	Click on Browser
4.	Search “drip.community”
5.	Open the menu on the top right and make sure you’re on the Swap tab
6.	Go to the Buy DRIP section
7.	Enter in almost all of your BNB. You’ll need to save some for gas fees (~$10)
8.	Click BUY
9.	Switch tab to the Faucet 
10.	 Go to the “Get a Buddy” Section
11.	Add 0x77822313a6a898A04d99ea43656507fc5D8c20dd
12.	Go to the Deposit section
13.	Click Max
14.	Click DEPOSIT
15.	A new window will pop up with MetaMask asking you to confirm gas fees. Click Confirm. If it says insufficient funds, you’ll need to add more BNB to your MetaMask Wallet. This doesn’t take much as each transaction is around or under $1
16.	Done!!

Strategy
For now, simply click the hydrate button each day around the same time. Do this within the metamask app, under the browser tab just like we did to buy DRIP.
